# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [3.7]
        os : ["ubuntu-latest", "macos-latest"]                
    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: fermipy
        environment-file: environment.yml
        python-version: ${{ matrix.python-version}}
        auto-activate-base: false
    - name: Install
      shell: bash -l {0}
      run: |
        python -m pip install --upgrade pip
        python -m pip install pylint pytest pytest-cov        
    - name: Lint with pylint
      shell: bash -l {0}
      run: |
        # stop the build if there are Python syntax errors or undefined names
        #pylint --reports=no --errors-only fermipy
        # stp the build if there are a lot of messages
        #pylint --reports=no --fail-under=9.5 fermipy
        # exit-zero treats all errors as warnings.
        pylint --exit-zero fermipy
    - name: Test with pytest
      shell: bash -l {0}    
      run: |
        python -m pytest --cov=./fermipy --cov-report=xml fermipy
    - name: Test gammapy dev with pytest
      shell: bash -l {0}
      run: |
        python -m pip uninstall gammapy
        python -m pip install git+https://github.com/gammapy/gammapy.git
        python -m pytest --cov=./fermipy --cov-report=xml fermipy
